"""Simplified Per-Repo Summary Generator - will be enhanced in next iteration"""
from pathlib import Path
from datetime import datetime
from collections import defaultdict
from typing import Dict, List

class RepoSummaryGenerator:
    def __init__(self, output_dir: Path):
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(parents=True, exist_ok=True)
    
    def generate_summary(self, repo_name: str, findings: Dict, stats: Dict, scan_duration: float) -> Path:
        """Generate Markdown report for repository."""
        report_path = self.output_dir / f"{repo_name}_AUDIT_REPORT.md"
        
        # Quick summary for Phase 1
        report = f"""# Security Audit Report: {repo_name}

Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
Duration: {scan_duration:.1f}s

## Summary

**Files Scanned**: {stats.get('files_scanned', 0)}
**Total Findings**: {sum(len(f) for f in findings.values())}

## Severity Breakdown

{self._generate_severity_table(findings)}

## Agent Performance

{self._generate_agent_stats(stats)}

---
*Generated by Multi-Agent Security Audit Framework*
"""
        
        with open(report_path, 'w') as f:
            f.write(report)
        
        return report_path
    
    def _generate_severity_table(self, findings):
        by_severity = defaultdict(int)
        for file_findings in findings.values():
            for f in file_findings:
                by_severity[f.severity.value] += 1
        
        table = "| Severity | Count |\n|----------|-------|\n"
        for sev in ['CRITICAL', 'HIGH', 'MEDIUM', 'LOW', 'INFO']:
            table += f"| {sev} | {by_severity.get(sev, 0)} |\n"
        return table
    
    def _generate_agent_stats(self, stats):
        agent_stats = stats.get('findings_per_agent', {})
        lines = "| Agent | Findings |\n|-------|----------|\n"
        for agent, count in agent_stats.items():
            lines += f"| {agent} | {count} |\n"
        return lines
